# Generated by Django 2.1.3 on 2018-11-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.PositiveIntegerField(choices=[(15, 'Hearts'), (16, 'Spades'), (17, 'Clubs'), (18, 'Diamonds')])),
                ('number', models.PositiveIntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, 'Jack'), (12, 'Queen'), (13, 'King'), (14, 'Ace')])),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deck', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='play.Stack'),
        ),
    ]
