# Generated by Django 2.1.3 on 2018-11-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='deck',
            new_name='stack',
        ),
    ]
