# Generated by Django 2.1.3 on 2018-11-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='chips',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
