# Generated by Django 2.1.3 on 2018-12-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_auto_20181124_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hand',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Stack',
        ),
    ]
